### ISSUE TITLE
Please remove

### ISSUE THREAD

**Issue by baconjuggling** [adamff1/ESP8266_WiFi_Captive_Portal_2.0#5]
Hey 125k, i love your work. Thankyou.

Can this be issue deleted?

**Comment by dsfifty** [comment]
Hi @baconjuggling I have just completed some additions to the src to allow saving with LittleFS.

**Comment by lorenzoPrimi** [comment]
@dsfifty where are these changes? Very interested to check out the code

**Comment by dsfifty** [comment]
Try here...
  

  
 https://drive.google.com/drive/folders/1CicnCVhwoACqXUyN-UNsbR2giN10wB01
  

  

  

  
  
  
  
  
>

**Comment by lorenzoPrimi** [comment]
Thanks @dsfifty gonna try it soon, you didn't push it on github, would be great to open a PR for this repo!
Do you want to do it or I can do it as well after testing the code.

**Comment by dsfifty** [comment]
Go right ahead,
  

  

  

  
  
  
  
  
>

**Comment by lorenzoPrimi** [comment]
Thank you, I opened a PR on this repo and updated my fork as well 
https://github.com/lorenzoPrimi/ESP8266_WiFi_Captive_Portal_Google_Login

**Comment by lorenzoPrimi** [comment]
Should be left open until the PR is merged
